#启动时端口号
server: port=8080
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  thymeleaf:
    prefix: classpath:/static/
    uffix: .html
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html
    encoding: utf-8
    check-template-location: true
#
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.mechanical.entity
#
logging:
  level:
    com:
      example:
        mapper: debug